title = "Ackerley Tng"
baseurl = "https://www.ackerleytng.com"
theme = "hugo-coder"
languageCode = "en-us"
defaultcontentlanguage = "en"

paginate = 10

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

# Ignore emacs lock files
ignoreFiles = ["^\\.#"]

[params]
    author = "Ackerley Tng"
    info = "Software Engineer"
    blurb = [
        "Coding is a craft.",
        "Good code is just enough code;",
        "concise and idiomatic."
    ]
    description = "Ackerley Tng's personal website"
    keywords = "blog,developer,engineer,personal"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/ackerleytng/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://linkedin.com/in/ackerleytng/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium fa-2x"
    weight = 2
    url = "https://medium.com/@ackerleytng"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"